version: '3.7'

services:
  db:
    container_name: mongodb
    image: mongo
    networks: 
      - goals-net
    volumes: 
      - data:/data/db
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=secret
  backend:
    container_name: goals-backend
    image: goals-node
    networks: 
      - goals-net
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on: 
      - db
    volumes: 
      - $PWD/backend:/app
      - logs:/app/logs
      - /app/node_modules
    environment: 
      - MONGODB_USERNAME=user
    ports: 
      - 8000:8000
  frontend:
    container_name: goals-frontend
    image: goals-react
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on: 
      - backend
    volumes: 
      - $PWD/frontend:/app
      - /app/node_modules
    environment: 
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - 3000:3000
    stdin_open: true
networks: 
  goals-net:
volumes: 
  data:
    external: true
  logs:
    external: true